### ISSUE TITLE
Have graphs of quotes and orders 

### ISSUE THREAD

**Issue by SMEWebify** [SMEWebify/WebErpMesv2#106]
Have graphs of quotes and orders on the distribution of prices and cost of tasks

**Comment by billyboy35** [comment]
Detail for eacth line for service 
![image](https://user-images.githubusercontent.com/75578469/205514309-0e6d703c-6ead-4bb5-af84-b74b408c406e.png)

**Comment by SMEWebify** [comment]
for total repatition quote service
![image](https://user-images.githubusercontent.com/75578469/205514344-d213275b-f647-4d58-acf8-cd87e9aac521.png)
