### ISSUE TITLE
doesn't start use on docker using docker compose

### ISSUE THREAD

**Issue by Merrick17** [SMEWebify/WebErpMesv2#16]
i tried to run using docker-compose , i added an empty .env file and runned docker-compose up 
![image](https://user-images.githubusercontent.com/25400839/153270754-f3685ea2-e848-4697-9ba7-16fc2afc9d66.png)

**Comment by SMEWebify** [comment]
Hi Merrick,

thank you for your interest. I don't know docker very well, @RobertoBochet as put a comment at the end of this [issue](https://github.com/billyboy35/WebErpMesv2/issues/9), can this one be helpful ?

I'm not sure the .env should be empty.

I will join mine in the evening

**Comment by Merrick17** [comment]
maybe i'm missing some env varibales , anything what do i have to add ?

**Comment by SMEWebify** [comment]
Find bellow my .env file

don't forget to create [your APP_KEY](https://stackoverflow.com/questions/33370134/when-to-generate-a-new-application-key-in-laravel)

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://127.0.0.1:8000/

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**Comment by RobertoBochet** [comment]
Hi @billyboy35 and @Merrick17, sorry but at the moment I am completely blocked by other projects, I hope to return soon on the study of WEM. 
The missing .env file is a standard for laravel project, I read that is not recommend to include it directly in the repo for several reasons, but maybe could be helpful include in the project an example version `.env.example` to avoid this issue.

**Comment by SMEWebify** [comment]
I have add one.

**Comment by SMEWebify** [comment]
Hi @Merrick17 
I close the issue, for lack of answers, if necessary we will reopen it =)
