### ISSUE TITLE
companiesAddresses.php does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by Merrick17** [SMEWebify/WebErpMesv2#17]
**Describe the bug**
I tried to run the project on local without using docker , so i found out some errors , when i used laragon latest version or even php 7.4 
Class App\Models\Companies\CompaniesAddresses located in D:/laragon/www/WebErpMesv2/app\Models\Companies\companiesAddresses.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Models\Companies\CompaniesContacts located in D:/laragon/www/WebErpMesv2/app\Models\Companies\companiesContacts.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by SMEWebify** [comment]
=( 

strange I fixed this on [issue 14 ](https://github.com/billyboy35/WebErpMesv2/issues/14)

**Comment by SMEWebify** [comment]
VSC files : 
![image](https://user-images.githubusercontent.com/75578469/153295457-21a053ce-eaf2-4bae-bab4-eda872aeb188.png)

Git files : 
![image](https://user-images.githubusercontent.com/75578469/153295560-bf32de44-6099-43cf-ae3b-eac1967f8c57.png)

**Comment by SMEWebify** [comment]
@Merrick17   VSC pluging git does not take case change in filename, I just made two commits for fix this with the gitlab interface

**Comment by SMEWebify** [comment]
@Merrick17 i can close this issue ?
