### ISSUE TITLE
[GENERAL] Support Vietnamese language

### ISSUE THREAD

**Issue by saosangmo** [SMEWebify/WebErpMesv2#198]
Could you support Vietnamese language, I will translate it into Vietnamese.
Thanks

**Comment by SMEWebify** [comment]
Hi @saosangmo 

it's a lot of work, currently only the dashboard supports multi language. But I can already activate the language and start working.

I'm aiming for that on this version.

**Comment by SMEWebify** [comment]
`php        'vi'          => ['name' => 'Vietnamese',             'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN'],`

**Comment by saosangmo** [comment]
I have started translate the first file into Vietnamese. Hope you complete your work soon.

**Comment by SMEWebify** [comment]
Pull merge SMEWebify/WebErpMesv2/pull/199

**Comment by SMEWebify** [comment]
@saosangmo The translation of the menu can be found in 
"\resources\lang\vendor\adminlte\vi\menu.php"
you can translate this @saosangmo ?

**Comment by saosangmo** [comment]
@SMEWebify please check PR https://github.com/SMEWebify/WebErpMesv2/pull/201

**Comment by SMEWebify** [comment]
@saosangmo I work again and again, already 114 pages of modifications

do you think it would be useful to create a readme for Vietnam?

**Comment by saosangmo** [comment]
@SMEWebify Thank for your nice works. I will create PR for Vietnamese readme soon.

**Comment by SMEWebify** [comment]
Hi @saosangmo  the project is now all translatable

I probably forgot a lot in the 120 pages. Don't hesitate to put it back together

**Comment by saosangmo** [comment]
@SMEWebify 
I have found some duplicate strings in `https://github.com/SMEWebify/WebErpMesv2/blob/WEM-2.0/resources/lang/en/general_content.php`

`male_trans_key`,
`female_trans_key`,
`purchase_receipt_trans_key`,
`select_unit_trans_key`,
`no_permissions_trans_key`,
`phone_trans_key`,
`no_task_trans_key`,
`order_confirm_trans_key`,
`new_companie_trans_key`

**Comment by SMEWebify** [comment]
@saosangmo nice spotting, it's fixed

**Comment by SMEWebify** [comment]
Hi @saosangmo I will push this issue to version 1.07

**Comment by SMEWebify** [comment]
Hi, @saosangmo  should I close this task?

**Comment by saosangmo** [comment]
Yes. please close it now!
