### ISSUE TITLE
500 error after set the Estimated Budget

### ISSUE THREAD

**Issue by darrelljung111** [SMEWebify/WebErpMesv2#237]
I started the app with "php artisan serve" following dev mode and setting company info and try to check dashboard so input Estimated Budget.
But after input the Estimated Budget, Dashboard is occurred error 500, Do I have to set anything else?
What does Estimated Budget mean? and what is best way to set it for making Dashboard work?

![스크린샷 2023-11-15 오전 9 14 12](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/205951c4-c1b3-4653-bc09-32d566f9b168)
![스크린샷 2023-11-15 오전 9 14 25](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/6373873e-7ae6-4f25-b58c-2b77d586c0cd)

**Comment by SMEWebify** [comment]
Hello @darrelljung111, thank you for your message

I haven't had a similar outcome, but whatever I'm going wrong, it's not certain that it has to do with the budget.

You have an error 500, so you are not in debug mode I think.

Pass in the  .env  file APP_DEBUG to true if this is not done.

otherwise you will find in storage / log / a laravel file with the details of the error

This will allow me to see what is wrong

**Comment by darrelljung111** [comment]
Hi, I appreciate your fast response!!
Please check the attached file.

There are ERROR in there on dashboard but I don't understand it. 
I guess it is php version problem, I am using

php -v
PHP 8.2.12 (cli) (built: Nov  5 2023 19:48:03) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies

[laravel.log](https://github.com/SMEWebify/WebErpMesv2/files/13361768/laravel.log)

**Comment by SMEWebify** [comment]
`[2023-11-15 07:34:39] production.ERROR: Undefined array key 0 {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WebErpMesv2/resources/views/dashboard.blade.php`

Line 147 (resources/views/dashboard.blade.php)

`{{ $OrderTotalForCast[0]->orderTotalForCast }}`

try :

`{{ $OrderTotalForCast[0]->orderTotalForCast ?? 0}}`

try this to move forward, I will look at the problem this evening

**Comment by SMEWebify** [comment]
Same :

line 536

`{{ $data['remaining_order'][0]->orderSum-$data['delivered_month_in_progress'][0]->orderSum  }}`

Try

`{{ $data['remaining_order'][0]->orderSum-$data['delivered_month_in_progress'][0]->orderSum  ?? 0}}`

**Comment by darrelljung111** [comment]
I changed as your direction but the result is same. 
production.ERROR: Undefined array key 0

Without this issue.

I found the 500 error in Method too. 
[2023-11-15 08:53:31] production.ERROR: Trying to access array offset on value of type null {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WebErpMesv2/resources/views/methods/methods-index.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1949716470 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1732</a><samp data-depth=1 class=sf-dump-expanded>

And order-lines too
[2023-11-15 09:01:41] production.ERROR: Attempt to read property "id" on null {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WebE

rpMesv2/resources/views/livewire/order-lines.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-112751713 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1678</a><samp data-depth=1 class=sf-dump-expanded>

Please check the attached file too.
[laravel.log](https://github.com/SMEWebify/WebErpMesv2/files/13362791/laravel.log)

**Comment by SMEWebify** [comment]
@darrelljung111  Wow, too many mistakes, what did I do =(

`[2023-11-15 08:53:31] production.ERROR: Trying to access array offset on value of type null {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WebErpMesv2/resources/views/methods/methods-index.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1949716470 data-indent-pad=" ">Illuminate\Support\ViewErrorBag {#1732`
I created[ this bug]( https://github.com/SMEWebify/WebErpMesv2/issues/238), if you can add information I will take it

` production.ERROR: Attempt to read property "id" on null {`
I already have [this issue](https://github.com/SMEWebify/WebErpMesv2/issues/195), not blocking, but I can't solve it

**Comment by SMEWebify** [comment]
`{{ $data['remaining_order'][0]->orderSum ?? 0 -$data['delivered_month_in_progress'][0]->orderSum   ?? 0}}`

**Comment by SMEWebify** [comment]
@darrelljung111  I just reproduced and corrected

ps: I also updated the documentation
for the settings, you will need to define the roles and permissions
TO DO
`php artisan db:seed --class=PermissionTableSeeder`
` php artisan db:seed --class=CreateAdminUserSeeder`

to have a full admin setting user:
```
contact@wem-project.org
password
```

**Comment by SMEWebify** [comment]
@darrelljung111  ps2 : [SMEWebify/WebErpMesv2/issues/239](https://github.com/SMEWebify/WebErpMesv2/issues/239)
