### ISSUE TITLE
Your company information cannot be set since VAT value has any option to set

### ISSUE THREAD

**Issue by darrelljung111** [SMEWebify/WebErpMesv2#242]
Hi, When I tried to set your company, VAT value has no option.
So your company value cannot be set.

It was working when I do only

php artisan db:seed

Now, I am doing

php artisan db:seed --class=PermissionTableSeeder
 php artisan db:seed --class=CreateAdminUserSeeder

![스크린샷 2023-11-17 오전 8 11 23](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/d1f75ed2-429f-4d5b-b982-1f788c387063)
![스크린샷 2023-11-17 오전 8 11 37](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/21411244-97f6-4003-9c1f-aad78ab4c052)

I guess it is database problem. 

 Your company information is not set, I guess there is problem on products/Stock too

500 Error, 
Oops! Internal Server Error.
We will work on fixing that right away. Meanwhile, you may return to [return to dashboard](http://localhost:8000/en/dashboard) or try using the search form.

[laravel.log](https://github.com/SMEWebify/WebErpMesv2/files/13385071/laravel.log)

**Comment by SMEWebify** [comment]
Good morning @darrelljung111 

I made this field to be able to define default values, but not yet use it, unfortunately the field is mandatory.

You must add a VAT on the accouting page.

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/421e291e-4ea2-4c1b-941a-6a25d991ad13)

**Comment by SMEWebify** [comment]
I have loged this issue for stock
[SMEWebify/WebErpMesv2/issues/243](https://github.com/SMEWebify/WebErpMesv2/issues/243)

**Comment by SMEWebify** [comment]
You will be required to have other information to make quotes, or orders, such as payment terms, or delivery payment method.

if attached a complete configuration example:

https://github.com/SMEWebify/WebErpMesv2/wiki/Accounting

**Comment by SMEWebify** [comment]
https://github.com/SMEWebify/WebErpMesv2/issues/243 is now fixed
