### ISSUE TITLE
Cannot add Leads  or Orders because I cannot find how I can add Contact name and Address name

### ISSUE THREAD

**Issue by darrelljung111** [SMEWebify/WebErpMesv2#249]
![스크린샷 2023-11-22 오후 11 18 11](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/00ff8a93-8b1f-47c0-b482-39a208cfe5a6)

Hi, I am not sure it is bug or just I cannot find how to add Contact name and Address name. 
But when I try to add Leads and Orders, there is no Contact name and Address name, So I cannot add Leads and Orders
Would you let me know how I can add Contact name and Address name?

**Comment by SMEWebify** [comment]
Hello @darrelljung111,

yes indeed you have to add a company in the “company” tab.

I know that on other systems, the company is made from the lead, but that is the case here.

I don't know why it was like that anymore. I could analyze to make a lead without having to put a company

**Comment by SMEWebify** [comment]
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/c0941d17-ddd5-414d-9d40-f56a3889553c)

**Comment by SMEWebify** [comment]
the current flow is

Company creation > lead > quote > order

what I wanted to do

Company creation > lead > oportunity > quote > order

What could be good

  lead > Company creation/oportunity > quote > order

**Comment by darrelljung111** [comment]
Hi, I don't understand. where is the place to input the company address and contact name. 

I input company information on Companies menu. there is no place to input Address and Contact name. 

There is no place to input "Company address name and Contact name" on Companies, Leads, Quotes, Orders 
Companies can only input company name, not company address and contact name. 
So Leads, Quotes, Order is not working since I cannot input company address and contact name.( It is saying that no address name, no contact, please add) I can only input company name on Leads, Quotes and Order.

Where can I input company address and contact name for the company which I input? 

And I cannot find the opportunity menu too.

![스크린샷 2023-11-23 오전 6 27 30](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/4450ba1e-058d-416b-b4c9-91c08da71bed)

**Comment by darrelljung111** [comment]
![스크린샷 2023-11-23 오전 6 36 42](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/0469c38b-e662-4e43-9776-f611445d7525)

I think it is same in the [sample](http://demo.wem-project.org/en/leads)

So I cannot input new lead

**Comment by darrelljung111** [comment]
Oh Sorry,

I find out where I can input the address and contact. It is in the company in detail. Now I understand your comment. I should input all company info first!
![스크린샷 2023-11-23 오전 6 41 34](https://github.com/SMEWebify/WebErpMesv2/assets/149659816/35f5fb42-7326-4a49-9a06-f183a35de464)

I think my problem is solved!!

**Comment by SMEWebify** [comment]
> Hi, I don't understand. where is the place to input the company address and contact name.
> 
> I input company information on Companies menu. there is no place to input Address and Contact name.
> 
> There is no place to input "Company address name and Contact name" on Companies, Leads, Quotes, Orders Companies can only input company name, not company address and contact name. So Leads, Quotes, Order is not working since I cannot input company address and contact name.( It is saying that no address name, no contact, please add) I can only input company name on Leads, Quotes and Order.
> 
> Where can I input company address and contact name for the company which I input?
> 
> And I cannot find the opportunity menu too.
> 
> ![스크린샷 2023-11-23 오전 6 27 30](https://user-images.githubusercontent.com/149659816/285047157-4450ba1e-058d-416b-b4c9-91c08da71bed.png)

the opportunities are currently being considered but not developed

https://github.com/SMEWebify/WebErpMesv2/issues/228

**Comment by SMEWebify** [comment]
> Oh Sorry,
> 
> I find out where I can input the address and contact. It is in the company in detail. Now I understand your comment. I should input all company info first! ![스크린샷 2023-11-23 오전 6 41 34](https://user-images.githubusercontent.com/149659816/285050880-35f5fb42-7326-4a49-9a06-f183a35de464.png)
> 
> I think my problem is solved!!

well seen, I think that I have some simplification work to do perhaps?

creating a lead without a company seems good to me

and the business is created when the opportunity is created
