### ISSUE TITLE
500 ERROR is occurred again on Method

### ISSUE THREAD

**Issue by darrelljung111** [SMEWebify/WebErpMesv2#250]
Hi,

I find out 500 Error is occurred again after I input your company info and companies info. 
It was disappeared when I followed below step.

php artisan db:seed --class=PermissionTableSeeder
php artisan db:seed --class=CreateAdminUserSeeder

instead of 

php artisan db:seed

during first dev install.

The Laravel log is attached
[laravel.log](https://github.com/SMEWebify/WebErpMesv2/files/13444627/laravel.log)

**Comment by SMEWebify** [comment]
Damn, you are a good tester!

Do you know how it came about? did you record any data?

Could you capture the data in the tables for me?

or you just run the commands and error?

**Comment by darrelljung111** [comment]
Hi, I tested from git download and followed all install way.
https://github.com/SMEWebify/WebErpMesv2/wiki/Installation-Steps-(for-dev)

1. Input your company info
2. Add company info
3. Add Lead info

Then, Method is displaying without 500 Error. 
It seams I input something wrong during I am looking for how to input Company address and contact name. 
Anyhow I am OK now!!

Please close this issue

Thank you!!

**Comment by SMEWebify** [comment]
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/f775d9c9-3127-4a6e-a5cd-8998efb0dde4)


![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/ba313662-7b52-445b-a9b2-c24a51423092)

ok, I found the problem, dbseed insert user id data from I don't know where even though there is no user in the table

is now fix
