### ISSUE TITLE
Unable to add Company on self hosted

### ISSUE THREAD

**Issue by Circlegent** [SMEWebify/WebErpMesv2#306]
Unable to add Company into system.  Fill in information, click Submit and nothing happens.  No errors on page.  Does not add anything to database and no error logs generated that I can see.  Tried to add the same info into the DEMO page and all went according to plan.

**To Reproduce**
Unsure how to reproduce.  I am using Xampp on Windows 10 machine at the moment.

**Expected behavior**
Company to be added to database.

**Screenshots**
Not sure screenshots will help as there is no information given on any error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All
 - Version 1.07

**Smartphone (please complete the following information):**

**Additional context**
None

**Comment by SMEWebify** [comment]
Hello @Circlegent 

were you able to enter the application ?
to locate the problem, when you want to add, is it this page ?

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/61ff668a-0446-4d5e-8132-368698f88ea0)

**Comment by Circlegent** [comment]
Yes.  That is the correct page.  I click on New Company, fill out all appropriate information, click submit button and nothing happens.  Even if I clear all data I do not get the error messages that pop up on the DEMO site.

**Comment by SMEWebify** [comment]
this form uses livewire, nothing in the browser console in error?

there are other forms that use this component, for example here, do they work?

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/7432ff09-f8a4-4ab8-9d8c-e90da47d2b90)

**Comment by SMEWebify** [comment]
what version of php do you use?

**Comment by Circlegent** [comment]
Yes. All of the pages listed work as expected.  
![wem](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/6c165595-ac10-4923-8ad2-b92de5cccc43)
Go from blue to red to black... When I click final submit.  Nothing happens.

**Comment by Circlegent** [comment]
PHP version 8.2.12

**Comment by Circlegent** [comment]
Just for clarification sake... I submitted this under BUG before seeing the selection for other issues.  Not sure if this is a true bug or just a configuration error somewhere.

**Comment by SMEWebify** [comment]
In "www\WebErpMesv2\app\Livewire\CompaniesLines.php" file

add  line 70 dump and die

```php
    public function storeCompany(){

        dd('test');

        $this->validate();
            // Create Line
            $CompaniesCreated = Companies::create([
```

do you have this one after submit ?
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/68c02a9a-4b52-40ce-853a-a32034c18aff)

**Comment by Circlegent** [comment]
I get nothing on my screen except the same as the screenshot I sent.  Nothing like in the screenshot you posted.

**Comment by SMEWebify** [comment]
so there is quite a conundrum there, especially if the other pages work.

can you add a row manually to the database?

the component is the same between display and storage, nothing should be displayed after manual saving

**Comment by Circlegent** [comment]
I was able to add a row to the database manually. MYSQL database btw.

**Comment by Circlegent** [comment]
Also just noticed that the Company that I added did not show up on the Dashboard under client.  Does show up in the list after clicking on the box.

**Comment by SMEWebify** [comment]
And the line is displayed in the companie list ?

**Comment by Circlegent** [comment]
Yes  
![wem2](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/c6d01c60-f839-429c-af49-52f11e392a65)

**Comment by SMEWebify** [comment]
It's surprising, I get a similar operation to the case you describe (that is to say, nothing happens) here I respect the livewire doc.

can you try these syntax in this file
"\www\WebErpMesv2\resources\views\livewire\companies-lines.blade.php"

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/647a6817-9c36-4141-88f6-2d4bed1414d5)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/3f095a65-e98f-4ee0-9cba-66d15dbdac8f)

**Comment by Circlegent** [comment]
what line numbers are those?

**Comment by Circlegent** [comment]
Found it.
![wem3](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/28c28950-bb95-402a-af4c-5e158073dad4)

**Comment by SMEWebify** [comment]
13 and 188

**Comment by Circlegent** [comment]
You want me to change the code to look like the right hand side picture?  Attached screenshot for verification.
![wem4](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/36bdf51a-d7d6-47b5-8d10-02b141d9b2da)

**Comment by Circlegent** [comment]
I am at the end of my work day here.   I will check on this in the morning.  Hopefully this can be resolved.  Thank you for your time on this.  It is appreciated.

**Comment by SMEWebify** [comment]
yes you have the <form tag ... and the <button type tag to modify to conform to my images on the right

I don't know what's wrong.

In your Laravel project's .env file, make sure the APP_DEBUG variable is set to true ?

if I do F12 and network, I see livewire requests which are carried out despite everything
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/8b681c13-3cdb-457a-bbcd-86257385073e)

**Comment by SMEWebify** [comment]
I found a similar case, without solutions, it sucks
https://laracasts.com/discuss/channels/livewire/wiresubmit-not-working?page=1&replyId=920480

**Comment by Circlegent** [comment]
Mystery has been solved.  Something with Xampp 8 that it didn't like.  I turned on the internal webserver and all works as expected.  However this also means that I cannot deploy it onto my network/Intranet like is needed for actual Production enviorment.  Not sure how to make it work with network but happy to report that the mentioned issue is resolved.
