### ISSUE TITLE
Error Exception   - Trying to access array offset on value type null

### ISSUE THREAD

**Issue by Circlegent** [SMEWebify/WebErpMesv2#309]
**Describe the bug**
Attempting to test the Stock section of the software I discovered this bug.  When going through steps to add all info into system I am met with the error in the Title.

**To Reproduce**
1. Go to '/en/products/stock   and attempt to enter stock into the system with locations and everything.
2. See error

**Expected behavior**
New products to be added along with locations of where it comes from, etc.

**Screenshots**
Screenshot of the error and file location as well as the PHP version has been added 

**Desktop (please complete the following information):**
 - OS: Xampp ( on Windows 10)
 - Browser Chrome, Edge, FF
![newWEMerror1](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/4bcee19d-2326-4648-92e5-fefa79b191b9)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SMEWebify** [comment]
Hello @Circlegent Do you have the relevant line in the attached image?

**Comment by Circlegent** [comment]
No sadly I don't.

**Comment by Circlegent** [comment]
Apparently the DEMO version and the one that I downloaded are very different somehow.  Is there a way to get the code for the DEMO site that you have up?  That one seems to work just fine.

**Comment by SMEWebify** [comment]
The online version is version 1.0.7 which I believe is the one you are testing.

Looking better, I see that the error is on line 49

`<td>{{ $StockLocationsProduct->Product['label'] }}</td>`

You can show the line that is in your "stock_location_products" database

I have tree connections with other tables (which

            $table->integer('user_id'); 
            $table->integer('stock_locations_id');
            $table->integer('products_id');

I assume that products_id must be empty in your database record ?

I made similar corrections on version 1.0.5 after user feedback.

this field must not be empty
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/7e649a82-4a0c-4a74-9b3f-affe13cc82b5)


I have to admit that I don't have much feedback on stock and wem

**Comment by Circlegent** [comment]
Thank you for the quick response.  In my testing I am finding a lot of features that I like in regards to helping production throughput.

**Comment by SMEWebify** [comment]
@Circlegent Don't hesitate to submit ideas, I would be happy to contribute even more if possible.

**Comment by SMEWebify** [comment]
I am reopening this issue, I will provide a fix this evening so that the user does not fall into this situation

``` php
class StoreStockLocationProductsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'code' =>'required|unique:stock_location_products',
            'stock_locations_id' =>'required',
            'mini_qty' =>'numeric|min:0',
        ];
    }
}
```

add
` 'products_id' =>'required',`

**Comment by SMEWebify** [comment]
Fixed
