### ISSUE TITLE
Having issues with the Purchasing products flow

### ISSUE THREAD

**Issue by Circlegent** [SMEWebify/WebErpMesv2#311]
Hello again.  
I did not know how to label this so I chose the blank issue.  Please label correctly, thank you. 

I am having an issue with the purchasing of inventory needed to manufacture the products.  When I try and go to make a purchase order I get met with 'No Lines Selected' however I cannot see where to even add products to the PO that I am trying to make.  Please fill me in on the flow as it is currently setup.   I can make a better decision after that.

Thank you.

**Comment by SMEWebify** [comment]
Purchase lines are possible if in the nomenclature of the order line there is a task requiring a purchase

For example :

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/05e7cf4a-c7f8-4da4-a4ae-21cb2d1e5070)

I have a command line
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/b9dbca0e-7a23-45dc-b623-4e2af88bb63c)


With BOM
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/33db1f17-49c1-4020-a7c7-122921d401d5)

for a task to be considered as a purchase, you must have a service requiring one of the types in yellow
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/4623217c-ae71-4c45-8ea3-c9159b17903c)

**Comment by SMEWebify** [comment]
you can add products from production which will supply stock, only from internal orders (always with purchase tasks)

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/a04ffb55-022d-419f-be3b-31bbf64df622)

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/27b968da-e9d3-4e8f-8d99-151da6bfa49e)

**Comment by SMEWebify** [comment]
something else, the product must necessarily exist for it to be stored

Don't hesitate to tell me what you produce (a concrete case that I can project (visualize)

**Comment by Circlegent** [comment]
We build internal cabinets and fixtures for ambulances.  All together we have a list of well over 2000 parts that go into these on a per cabinet basis ( there are 4 actual final pieces that make up the "cabinet")   I see no way of separating the products to purchase per provider.  I tried a example on your DEMO site and was able to "order" a product that wasn't associated with the supplier that I had chosen.   The flow that usually happens is as follows:  All parts to cabinet section gets pulled and delivered to bay for assembly,  this lowers the stock amount accordingly,  stock numbers are reflected back to the Purchasing Manager,  PO gets created **per supplier** for replenishment of stock.   When there are multiple suppliers then they are both associated with the product and Purchase Manager makes the decision on who to order from.   Please let me know if this is a help.  Thank you very much.

**Comment by Circlegent** [comment]
I like your software for the ability to break things down into sub assemblies as well as primary parts.  Your BOM as you have it also is a feature that is needed.  However the inability to break down the products that are purchased ( I.E. screws,  wood material for CNC cutting, metal edging, etc ) by supplier is not something that can be allowed as it would allow for order mistakes and lead to late arrival of orders or even orders not arriving at all due to being sent to the wrong supplier.   I hope I have given you a clear enough picture of the standard process here.  Again thank you.

**Comment by SMEWebify** [comment]
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/8663294a-b289-4bc8-a77e-547274cf7a3a)

If I made a picture, would it look like this?

2 things :

Currently, there is no preferred supplier per item.

> It's quite easy to add preferred suppliers per product
> Could this be a solution, that when I select a supplier, only the articles concerned by the one if are present?

currently, I do not manage 2-level nomenclatures

> I have already prepared some work, but there is still a lot to think about in order to have to manage a recursive nomenclature.
> How many levels do you manage?

**Comment by Circlegent** [comment]
That is very accurate.  As far as the sub assembly things my main reason for those is to reference back to things needed that are made here as well and then added to the main assembly.  Utilizing that would only be to that end and not multi levels of parts.   Your idea above is the right idea.  Being able to create a PO that only has the ability to pick from the products of that supplier is what is needed.   I thought in the beginning that feature was already there by the "Sort Companies' pull down on the page.  When I realized that the products didn't change is why I only mentioned it when I did.

**Comment by SMEWebify** [comment]
First step https://github.com/SMEWebify/WebErpMesv2/issues/313

**Comment by SMEWebify** [comment]
Step two, a little more complicated  https://github.com/SMEWebify/WebErpMesv2/issues/314

**Comment by SMEWebify** [comment]
@Circlegent  can you test on demo page

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/3f67c7a5-8884-4c4b-b502-dec72e4fc9f1)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/9276f875-668c-4699-aeb0-1b92dc71c38a)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/15fb4b43-3bec-4c45-851e-02aa837dc5b2)

It seems that I have a bug after creating the order
But is the principle what you expect?

**Comment by SMEWebify** [comment]
Fixe bug for selection https://github.com/SMEWebify/WebErpMesv2/issues/315

**Comment by Circlegent** [comment]
Hello,
I tested your addition first thing when I got in.  I like it.  Limits the products like it is meant to do.  However when I go to add a Internal Order to the system for a new product ( simulated :) ) I get a 500 error when trying to add Order Line.
![wem500error1](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/26573a1e-2cb0-4dd6-a063-afe8d002f341)

This is the page I am on just before the error: 
![wem500error2](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/64fd6f38-2596-479b-ab7d-0d6c9991ebf6)

**Comment by SMEWebify** [comment]
regression after optimization, sorry, it's fixed

I haven't yet worked on the stock to deduct from the purchase, it's a lot of work, I need to think a little

**Comment by Circlegent** [comment]
I noticed that where you go to add things to the Tech/ BOM screen the products do not change when you select the different Services.  I tried to add a mock cabinet and some of the components to see what would happen but I can't add any of the new products at this stage.  All I see is the same products no matter what Service I choose.  I even tried setting the product to different Services and then switching off and back to that Service in order to get it to update.  Having this could also help with the reduction to the stock.  i.e. Any manufactured final parts HAS to have a BOM list.  This would give it a starting point to have a number to lower the stock by.  Please let me know if there is something I am missing in the BOM screen to get that to change.  Thank you

**Comment by Circlegent** [comment]
Apologies,
I meant to add these screenshots. 
![wem-bomSS](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/2e13f7cb-b1a5-4990-97db-aab98f79c0eb)
![wem-bomSS-1](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/baa77822-5148-41ac-886c-b6415338bee0)
These show the products not changing.

**Comment by SMEWebify** [comment]
Actually, I'm going to see why I haven't done it.

**Comment by SMEWebify** [comment]
I just looked, I display all the services which have a type 8 =>
#8 = Composed component

I assume when specifying that an item to be purchased is necessarily a purchase service. 

So a single "purchase" type service do you see another case which should have two type services
“Compound components” ?

**Comment by Circlegent** [comment]
I am not sure I understand what you are asking.  However my understanding is that any products that would be purchased for the manufacturing process would fall under "Purchase" service.  There might be different Families they fall under but that would be sufficient for that.  I hope I have answered your question.

**Comment by Circlegent** [comment]
To add onto my previous post any components that are manufactured in house to be put on this final product would also go on this list.  A  "in house" Service ( or something similar) is where that would ideally be place.   Being able to add from these different Services was the focus of my original post.

**Comment by SMEWebify** [comment]
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/345f77fd-86f7-47fb-b29c-5ce2a849f890)

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/e55b06df-0408-4b0a-943a-2cd36e616434)

By carrying out a test, I arrived at this case, I want part SHT-1000 in my BOM

it can be purchased, or a component, but today seems a dead end, I manage it by no means, it is neither to buy, nor the product (stock?)

For the parts to be manufactured, in an assembly, you must use "sub assembly" but unfortunately, I am not yet dealing with the tasks of these assembles at the moment (so there is nothing to produce)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/98766bee-8687-4ea0-8a34-f050fba2c913)

**Comment by Circlegent** [comment]
Your software as it is can handle any sub assemblies.  They are not termed sub assemblies but that is not a bad thing.  These are simply a "In House" object and labeled as such.  Anything that HAS to be purchased (i.e. screws, nuts, bolts, raw material like plywood etc.) is what would be placed into "Purchase" Service.  If there is a choice of Purchasing it or manufacturing in house then that is up to management team how they want to proceed and it gets put into the system however they choose. ( for a real world example we have a product that we COULD make in house but choose to purchase it local, If that changes then it would require a change in the system from Purchased to In house. )

**Comment by SMEWebify** [comment]
it would come down to this
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/67cf2256-aa2a-4039-b8d9-bd1a9d4265c3)

**Comment by Circlegent** [comment]
Not entirely...
![BOM-Flow](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/cfdb9d1a-7346-49e7-bc41-a582e4b30654)

The "Sub Assembly" would not be needed if you had the part as a Component. 

Or vice versa from what I put in the screen shot.  The sub assembly added and not the component.

**Comment by Circlegent** [comment]
I will ask it this way.

I have my Cabinet product that I put in the system.
![wem-bomSS-2](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/87ce37d7-f724-4641-b5b5-38ae367955f6)

I also have my stainless steel screw that I have put into the system as a purchased product.
![wem-bomSS-3](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/f6342654-76c3-41ad-9900-04ef64bb4ef3)

How do I get the Stainless steel screw into the BOM of the Cabinet?

**Comment by Circlegent** [comment]
I have modified the Product Cabinet-54321 to reflect the multiple sub assemblies possible.

**Comment by Circlegent** [comment]
I have to apologize.  I misunderstood how the flags for the BOM components worked.  I was under the impression that they reflected the different Services.

**Comment by SMEWebify** [comment]
I took the time to think, sorry for the slow response

- A component in the BOM category with a component type service, is a stored item (it does not allow it to be produced, only to be removed from stock, a functionality not currently possible)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/43493517-1723-4b76-8e0e-0529bc64e917)

- A component in the BOM category with a purchasing service, is a component to purchase which will then be found in the parts to purchase
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/8ad05dd6-9d65-4540-8031-05845fb93b4b)

- A component in the sub assembly category, are stored components, but which will be produced (functionality not currently possible)
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/e8d015cf-81ab-4251-b81e-5f17d9fd5f3a)

the overall flow would be as follows
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/adcbbd81-403b-4d73-96da-6d4db9d07a15)

**Comment by Circlegent** [comment]
That is on the correct path.  I am attaching a pic of the flow as discussed with upper management here.  I have tried to make things as clear as I can.  Please feel free to ask any questions.

![Product Mfr-purch-flow](https://github.com/SMEWebify/WebErpMesv2/assets/72153487/f105ae76-6f71-49dc-a2a0-051ec7353c1c)

If the picture will not load please let me know and I will send it to you another way.

**Comment by SMEWebify** [comment]
I don't know if I could go as far as you want, especially for the second point

the first step is to already create the in and out of stock
https://github.com/SMEWebify/WebErpMesv2/issues/318

PS :I did this this afternoon on the product sheet
 ![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/7556ad81-45a9-4e06-b3ce-a25e298efa3c)



the second notion of replenishment is very complex, this is what will take a lot of time
currently on wem I can have several stocks per product
which poses a concern to me, all stocks would have to be in the red, to say that a component is red
- [ ] generally speaking, everything will not be done on the "sud assembly" but on the "BOM"
https://github.com/SMEWebify/WebErpMesv2/issues/319
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/ad2f0876-0c6d-4bb4-8519-d7fb6659d1e0)

if the box is red, I could create an internal order from the BOM line
https://github.com/SMEWebify/WebErpMesv2/issues/320

I will create a pop with a programmed task to display the stocks below the minimum QT (without taking into account current orders)
https://github.com/SMEWebify/WebErpMesv2/issues/321

already with that it will be a start
