### ISSUE TITLE
Feature Request: User Activity Logging and Invoice Payment Status

### ISSUE THREAD

**Issue by compnew2006** [SMEWebify/WebErpMesv2#355]
This feature request proposes two functionalities:
1- User Activity Logging: Implement a system to track user actions within the application. This will allow for improved auditing and monitoring of changes made to data by users, and for administrators and project managers to have the ability to track which user made specific changes within the application.
2- Invoice Payment Status: Introduce a feature to indicate the payment status of invoices within a clear format (e.g., "Paid", "Unpaid", "Pending"). This will enhance clarity and facilitate financial management.

**Comment by SMEWebify** [comment]
For point 2 i create sub task : https://github.com/SMEWebify/WebErpMesv2/issues/356

**Comment by SMEWebify** [comment]
Poke @compnew2006 

I already have an activity log which is stored in the database.
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/15fa6305-78bf-4c3e-ae9b-ffd8691b9229)
the models that are tracked are as follows.
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/fbd431b1-0e2a-4e93-b81a-1c56fb95d747)
With this data not easy to use, how should I communicate the information to the user, and to which user?

**Comment by SMEWebify** [comment]
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/f2118b9e-d712-4374-b078-43acab1fed04)

**Comment by SMEWebify** [comment]
if fields need to be monitored, we can vary the data in the models:

     public function getActivitylogOptions(): LogOptions
     {
         return LogOptions::defaults()->logOnly(['code', 'label', 'status']);
         // Chain fluent methods for configuration options
     }
