### ISSUE TITLE
[TRANSLATION] What can I do to assist with the translation process to arabic?

### ISSUE THREAD

**Issue by compnew2006** [SMEWebify/WebErpMesv2#357]
What can I do to assist with the translation process to Arabic?
I have some knowledge in programing with php (don't know about Laravel) and I speaking Arabic English and Spanish.

**Comment by SMEWebify** [comment]
Hi @compnew2006 

It's a big jo b!

The language must be activated in laravellocalization.php
[laravellocalization.php](https://github.com/SMEWebify/WebErpMesv2/blob/WEM-2.0/config/laravellocalization.php)

the translations are found in and are stored by country in this directory
[resources/lang/](https://github.com/SMEWebify/WebErpMesv2/tree/WEM-2.0/resources/lang/)

This file contains the translation keys, the same file is required in the translation countries
[general_content.php](https://github.com/SMEWebify/WebErpMesv2/blob/WEM-2.0/resources/lang/en/general_content.php)

This directory contains the keys for the adminlte menu
[resources/lang/vendor/adminlte](https://github.com/SMEWebify/WebErpMesv2/tree/WEM-2.0/resources/lang/vendor/adminlte)

**Comment by SMEWebify** [comment]
Hi @compnew2006 I can activate countries if you wish. Please tell me if you would like to go further on this task.

**Comment by SMEWebify** [comment]
Hi @compnew2006  do you need help ?

**Comment by compnew2006** [comment]
Yes, please. The directory [resources/lang/](https://github.com/SMEWebify/WebErpMesv2/tree/WEM-2.0/resources/lang/) does not have an Arabic folder.
Please add it
i have the general_content.php already translated

**Comment by SMEWebify** [comment]
Hi @compnew2006   I enable these fields though? 

could only the ar_AR be enough?
      
       //'ar'          => ['name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
        //'uz-Arab'     => ['name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => ''],
        //'tg-Arab'     => ['name' => 'Tajik (Arabic)',         'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ'],
        //'pa-Arab'     => ['name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN'],
        //'ks'          => ['name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN'],

**Comment by SMEWebify** [comment]
@compnew2006 I activated "ar" and "es" in interface. The folders were also created with the folders containing the English words

**Comment by compnew2006** [comment]
> @compnew2006 I activated "ar" and "es" in interface. The folders were also created with the folders containing the English words


I've done with "ar" and "es" in interface.
You must take into account that with the Arabic language, the display must be RTL.

**Comment by SMEWebify** [comment]
RTL mean ? from right to left is that it? (sorry, I only know Latin :'(   )

**Comment by compnew2006** [comment]
@SMEWebify  Yes, the Arabic language is right to left

**Comment by SMEWebify** [comment]
I need to find out what admin can do with this.  Should the menu also be on the right?  (not to mention the text)

**Comment by SMEWebify** [comment]
@compnew2006  unfortunately on this discussion recently  [jeroennoten/Laravel-AdminLTE/issues/1023](https://github.com/jeroennoten/Laravel-AdminLTE/issues/1023), RTL is not supported by the packaging. It will be with version 4 of adminLTE and boostrap 5

**Comment by SMEWebify** [comment]
Hi @compnew2006 I'm going to close the next sprint, do you think it's possible to push the Spanish translation? :)

**Comment by SMEWebify** [comment]
Hi @compnew2006 , what future for this issue?

**Comment by compnew2006** [comment]
I have already provided the Arabic and Spanish files but not shown any of them in the new 1.09

**Comment by SMEWebify** [comment]
can you send me a pull request so that I can integrate them pliz ? (or copy them here)

**Comment by SMEWebify** [comment]
hi @compnew2006 , I don't understand, when you say that you already provided the files.

**Comment by SMEWebify** [comment]
No response, I did what I could with the automatic translator
