### ISSUE TITLE
Loading dashboard is slow when MySQL server is running in a remote site.

### ISSUE THREAD

**Issue by sunxiaoguang** [SMEWebify/WebErpMesv2#362]
**Is your feature request related to a problem? Please describe.**
Loading dashboard is slow when MySQL server is running in a remote site. The extra latency introduced when accessing MySQL from public internet made loading dashboard slower than usual.

**Describe the solution you'd like**
It would be nice to optimize roundtrips between app server and MySQL server to make it less sensitive to slow network.

I realized FactoryServiceProvider can be optimized to load the first factory once per request. See PR #361 for reference.

**Comment by SMEWebify** [comment]
I think the dashboard deserves to be redone anyway, with things in vuejs or something else.

I will still try to reduce the requests in the controller

thank you for your work, being only an amateur, it is valuable for the project to be able to optimize

**Comment by sunxiaoguang** [comment]
> I think the dashboard deserves to be redone anyway, with things in vuejs or something else.
> 
> I will still try to reduce the requests in the controller
> 
> thank you for your work, being only an amateur, it is valuable for the project to be able to optimize

Cool, I found the project to be very easy to use and it works well for my scenarios. Thank you for creating this project; it has really helped me, and I believe it will help more and more people in the future.

If possible, I would like to contribute more to this project as I continue to use it. :)

**Comment by SMEWebify** [comment]
That's what I tried to do, lest go, if you're not sure, let's have a [discussion](https://github.com/SMEWebify/WebErpMesv2/discussions)
