### ISSUE TITLE
[INSTALL] The left menu the correct items are not showing up

### ISSUE THREAD

**Issue by ouyuki** [SMEWebify/WebErpMesv2#379]
Hi! After installing and opening the left menu the correct items are not showing up, not sure what I'm doing wrong?Thanks!!
[image](https://github.com/SMEWebify/WebErpMesv2/assets/13534630/583d3cb0-7e91-41b4-9c2e-d7787380d639)

**Comment by SMEWebify** [comment]
Hi @ouyuki 

Thank you for your feedback, the menu shown to you is without rights.

the application manages rights, you must initialize the permissions and role in order to connect as admin (contact@wem-project.org // password) with these artisan commands:

```
php artisan db:seed --class=PermissionTableSeeder
 php artisan db:seed --class=CreateAdminUserSeeder
```

In CreateAdminUserSeeder.php

you will have the login credentials for the admin

```php
    public function run()
    {
        $user = User::create([
            'name' => 'Admin', 
            'email' => 'contact@wem-project.org',
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // === password
        ]);
    
        $role = Role::create(['name' => 'Admin']);
     
        $permissions = Permission::pluck('id','id')->all();
   
        $role->syncPermissions($permissions);
     
        $user->assignRole([$role->id]);
    }
}
```

**Comment by ouyuki** [comment]
Thank you for your reply.
But it still shows ”These credentials do not match our records.“, I still did something wrong ;-(
![20240510083803](https://github.com/SMEWebify/WebErpMesv2/assets/13534630/67ed190a-dc26-4ee6-9bd9-d3f241d8778e)

**Comment by SMEWebify** [comment]
The email is encrypted and does not seem to work, regression introduced by  https://github.com/SMEWebify/WebErpMesv2/issues/371 ?

to resolve the issue while I find the problem, you can manually change the encrypted address in the database
![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/26eb358b-11bf-48bb-91b3-51bbb6c6f723)

**Comment by ouyuki** [comment]
It seems that encryption was not working and the problem has been solved, thanks!

**Comment by SMEWebify** [comment]
All connection management is managed by inertia in the packages, it seems like an important job to me, I prefer to remove the encryption of email addresses for the moment

**Comment by SMEWebify** [comment]
Thx @ouyuki I close the issue, looking forward to seeing you again
