### ISSUE TITLE
Sur la page de login de la demo, je clique sur le logo et j'ai une 500

### ISSUE THREAD

**Issue by abenevaut** [SMEWebify/WebErpMesv2#441]
Hello,

👋 je viens de découvrir ton projet au travers de ton message sur le discord Laravel-france.com.

When visiting the demo for the first time, I clicked on the header of your form

<img width="460" alt="Capture_d’écran_2024-06-18_à_12_10_41" src="https://github.com/SMEWebify/WebErpMesv2/assets/1134021/8793d6db-3433-42f1-bf8d-a0295b203d14">

This action leads to a 500 error, reproducible.

**Comment by SMEWebify** [comment]
Bonjour @abenevaut,

Oula oui, dans le mille, merci, c'est  corrigé.

Kévin
