### ISSUE TITLE
Please add a database SQL script file to the project

### ISSUE THREAD

**Issue by JustinSunli** [SMEWebify/WebErpMesv2#494]
Can the project offer users an SQL script for the database? Otherwise, executing 'php artisan migrate' in the project will always result in errors.

**Comment by SMEWebify** [comment]
Hi @JustinSunli What are the errors encountered with the artisan command?  I will look for the script, but it could make the application obsolete if the migrations are modified

**Comment by SMEWebify** [comment]
@JustinSunli please, find this sql file :  [erp.zip](https://github.com/user-attachments/files/16322178/erp.zip)

**Comment by JustinSunli** [comment]
thank you!
