### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by Doncz19** [SMEWebify/WebErpMesv2#581]
![image](https://github.com/user-attachments/assets/edc74082-0b12-421a-b275-4ac53d6164d5)

Hello!

Please help.  Thank you

**Comment by SMEWebify** [comment]
Hi 

The right link is SMEWebify/WebErpMesv2 where you find billyboy35 ?

Kevin

**Comment by SMEWebify** [comment]
@Doncz19  is working ?

**Comment by SMEWebify** [comment]
Update wiki, no new, i close this issue
