### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by ugintl** [SMEWebify/WebErpMesv2#70]
I would like to know if your system suits my use case.

**A medium sized screen printing and embroidery company wants to:

- I want to digitize our workflow (paper work and job flow)
- Move most of our work order processes to digital (order communication, statuses, checking in items / stock, art proofing, calendar, notes, etc)
-  Have a customer portal so they can check the status of their orders, approve production and communicate through the app/site. (Not looking for any payments or transactions yet)
- Internal calendar for overall work load in the shop, automations and color coding. Possibly automated job timing.**

 1. Would it need lot of customization? 
 
2.  What was in your mind when you were developing this system?

**Comment by SMEWebify** [comment]
Hello @ugintl ,

Thank you for your question, I remember you, you had already asked me the question  at the start of the project.
--

How many employees does the business have?

The system is made for digitizing a business and organizing the workflow.

If the next version will use a calendar (in August) with version 1.01, the stock is not available (I need to go further to make available what I have already done on the stock), the load plan will be available with version 1.02 and the implementation of the gantt system

Providing a customer portal is, in my opinion, another project. For what need? what functionality? for whom, client, prospect?

Have you tested the online demo? http://demo.wem-project.org/
would there be functions that I could develop quickly for you to use?

**Comment by ugintl** [comment]
Yes, I asked you a question, but it was different.

That is great

Customer portal means that customer can login and see progress and comment or message etc. I guess user roles permisssions will solve it.

I have tested the online demo. It is a really dynamic project.

Does this app has APIs?

**Comment by SMEWebify** [comment]
I am happy with your feedback on the demo, do not hesitate to make other comments to improve.

Yes the roles could do the thing quite simply, I thought it was in my roadmap, but no, I will add this functionality. And why not, an external page  for the next version (probably v1.04).

Currently no API, this could be a good start at first. An API on the commands would be sufficient?

**Comment by ugintl** [comment]
The problem is that I do not fully understand the API concept for now. So I would not be able to comment on this. What I have understood so far is that having APIs means that this app will be used as a backend and a front end will be connected to it. Are there other meanings as well?

**Comment by SMEWebify** [comment]
an API makes data available to another application.

for example an external project can request a url address www.yourwebsite.com/api/contact=1

and the site will return Json type data:

```
{
     "data": [
         {
             "id": 1,
             "name": "Eladio Schroeder Sr.",
             "email": "therese28@example.com",
         },
         {
             "id": 2,
             "name": "Liliana Mayert",
             "email": "evandervort@example.com",
         }
     ]
}
```

these data must be interpreted

**Comment by SMEWebify** [comment]
@ugintl I implemented an api for order data, you will find the result data for a specific order :
https://github.com/billyboy35/WebErpMesv2/issues/75

**Comment by ugintl** [comment]
Thanks. That was quick.

**Comment by SMEWebify** [comment]
@ugintl  =) this allows me to prepare the work for future requests.

could you explain to me these processes, that I know little about in your profession, and how do you see this in digital ?

- checking in items 
- art proofing
- notes

**Comment by SMEWebify** [comment]
@ugintl Do you want me to try to improve things to meet your needs, or do I close this topic ?

**Comment by ugintl** [comment]
Thank you for your warmheartedness. You are such a nice person that you are always trying to help. Truly a professional. It is very rare these days. Your efforts are much appreciated. You can close the topic for now.

**Comment by SMEWebify** [comment]
@ugintl  thank you for your message. Do not hesitate to come back and test the next version =)
